service_center/cars/urls.py
from django.conf.urls import url

from .views import (
    car_create,
    car_delete,
    car_detail,
    car_list,
    car_update
)


urlpatterns = [
    url(r'^create/$', car_create, name="create"),
    url(r'^(?P<id>\d+)/$', car_detail, name="detail"),
    url(r'^$', car_list, name="list"),
    url(r'^(?P<id>\d+)/edit/$', car_update, name="update"),
    url(r'^(?P<id>\d+)/delete/$', car_delete, name="delete"),
]

service_center/employee/urls.py
from django.conf.urls import url

from .views import (
    employee_create,
    employee_delete,
    employee_detail,
    employee_list,
    employee_update
)


urlpatterns = [
    url(r'^create/$', employee_create, name="create"),
    url(r'^(?P<id>\d+)/$', employee_detail, name="detail"),
    url(r'^$', employee_list, name="list"),
    url(r'^(?P<id>\d+)/edit/$', employee_update, name="update"),
    url(r'^(?P<id>\d+)/delete/$', employee_delete, name="delete"),
]

service_center/expense/urls.py
from django.conf.urls import url

from .views import (
    expense_category_create,
    # expense_category_detail,
    expense_category_list,
    expense_category_update,
    expense_category_delete,

    expense_create,
    # expense_detail,
    expense_list,
    expense_update,
    expense_delete

)


urlpatterns = [
    url(r'^category/create/$', expense_category_create, name="create"),
    # url(r'^category/(?P<id>\d+)/$', expense_category_detail, name="detail"),
    url(r'^category/$', expense_category_list, name="list"),
    url(r'^category/(?P<id>\d+)/edit/$', expense_category_update, name="update"),
    url(r'^category/(?P<id>\d+)/delete/$', expense_category_delete, name="delete"),

    url(r'^create/$', expense_create, name="expense_create"),
    # url(r'^(?P<id>\d+)/$', expense_detail, name="expense_detail"),
    url(r'^$', expense_list, name="expense_list"),
    url(r'^(?P<id>\d+)/edit/$', expense_update, name="expense_update"),
    url(r'^(?P<id>\d+)/delete/$', expense_delete, name="expense_delete"),

]

service_center/order/urls.py
from django.conf.urls import url

from .views import (
    order_create,
    order_delete,
    order_detail,
    order_list,
    order_update,
)


urlpatterns = [
    url(r'^create/$', order_create, name="create"),
    url(r'^(?P<id>\d+)/$', order_detail, name="detail"),
    url(r'^$', order_list, name="list"),
    url(r'^(?P<id>\d+)/edit/$', order_update, name="update"),
    url(r'^(?P<id>\d+)/delete/$', order_delete, name="delete"),
]

service_center/service_center/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from order.views import order_create

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^$', order_create, name="create"),
    url(r'^order/', include("order.urls", namespace="order")),
    url(r'^customer/', include("customers.urls", namespace="customer")),
    url(r'^employee/', include("employee.urls", namespace="employee")),
    url(r'^facility/', include("facilities.urls", namespace="facility")),
    url(r'^car/', include("cars.urls", namespace="car")),
    url(r'^reports/', include("reports.urls", namespace="reports")),
    url(r'^messages/', include("quick_messages.urls", namespace="messages")),
    url(r'^expense/', include("expense.urls", namespace="expense")),
    url(r'^discounts/', include("discounts.urls", namespace="discounts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Speedo Car Wash'

service_center/cars/models.py
from django.db import models
from customers.models import Customer
from django.core.urlresolvers import reverse
# Create your models here.


class Car(models.Model):

    CAR_CHOICES = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('B', 'Bike')

    )

    category = models.CharField(max_length=1, choices=CAR_CHOICES)
    model_code = models.CharField(max_length=120, unique=True)
    car_owner = models.ForeignKey(Customer)
    others_detail = models.CharField(max_length=120)
    visit_count = models.IntegerField(default=0)

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.model_code

    def get_absolute_url(self):
        return reverse("car:detail", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp"]

service_center/customers/models.py
from django.db import models
from django.core.urlresolvers import reverse

from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.


class Customer(models.Model):

    full_name = models.CharField(max_length=120)
    phone_number = PhoneNumberField(unique=True)
    city = models.CharField(max_length=60)

    others_detail = models.CharField(max_length=100)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.full_name + "   (" + str(self.phone_number) + ")"

    def get_absolute_url(self):
        return reverse("customer:detail", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp"]

service_center/discounts/models.py
from django.db import models

from django.core.urlresolvers import reverse

# Create your models here.

class Discount(models.Model):

    visit_count = models.PositiveIntegerField(unique=True)
    discount_percentage = models.PositiveIntegerField()
    activate = models.BooleanField(default=False)

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __int__(self):
        return self.visit_count

    def get_absolute_url(self):
        return reverse("discounts:discounts_list")

    class Meta:
        ordering = ["-timestamp"]

service_center/employee/models.py
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField

from django.core.urlresolvers import reverse
# Create your models here.


class Employee(models.Model):
    full_name = models.CharField(max_length=120)
    phone_number = PhoneNumberField()
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    salary = models.PositiveIntegerField()
    cnic_no = models.PositiveIntegerField()

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.full_name

    def get_absolute_url(self):
        return reverse("employee:detail", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp"]

service_center/expense/models.py
from django.db import models

from django.core.urlresolvers import reverse

# Create your models here.

class ExpenseCategory(models.Model):

    name = models.CharField(max_length=120, unique=True)
    description = models.TextField()

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("expense:list")

    class Meta:
        ordering = ["-timestamp"]


class Expense(models.Model):
    expense_category = models.ForeignKey(ExpenseCategory)
    price = models.IntegerField(default=0, null=True, blank=True)

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.expense_category.name

    def get_absolute_url(self):
        return reverse("expense:expense_list")

    class Meta:
        ordering = ["-timestamp"]

service_center/facilities/models.py
from django.db import models

from django.core.urlresolvers import reverse

# Create your models here.
class Facilitie(models.Model):

    name = models.CharField(max_length=120)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True,
                              width_field="width_field",
                              height_field="height_field")
    activate = models.BooleanField(default=False)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("facility:detail", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp"]


class Subfacilities(models.Model):
    name = models.CharField(max_length=120, unique=True)
    price = models.PositiveIntegerField(default=0, null=True, blank=True)
    small_vehicle_price = models.PositiveIntegerField(default=0, null=True, blank=True)
    medium_vehicle_price = models.PositiveIntegerField(default=0, null=True, blank=True)
    large_vehicle_price = models.PositiveIntegerField(default=0, null=True, blank=True)
    bike_vehicle_price = models.PositiveIntegerField(default=0, null=True, blank=True)
    category_wise = models.BooleanField(default=False)
    facility = models.ForeignKey(Facilitie, null=True, blank=True, on_delete=models.CASCADE)
    activate = models.BooleanField(default=False)

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.name

    class Meta:
        ordering = ["-timestamp"]

service_center/order/models.py
from django.db import models
from customers.models import Customer
from facilities.models import Facilitie
from cars.models import Car

from django.conf import settings

from django.core.urlresolvers import reverse

# Create your models here.


class Order(models.Model):
    created_user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    token_number = models.IntegerField(default=0)
    visit_car_count = models.IntegerField(default=0)
    customer = models.ForeignKey(Customer)
    facility = models.ManyToManyField(Facilitie, related_name='facility')
    vehicle = models.ForeignKey(Car)
    owner_reference = models.CharField(max_length=50, null=True, blank=True)
    total_amount = models.IntegerField(default=0)
    approved = models.BooleanField(default=False)
    facility_and_prices = models.TextField()
    declare_discount_string = models.IntegerField(null=True, blank=True)

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.customer.full_name

    def get_absolute_url(self):
        return reverse("order:detail", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp"]

service_center/quick_messages/models.py
from django.db import models
from django.core.urlresolvers import reverse
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.

class Templates(models.Model):

    template_name = models.CharField(max_length=120, unique=True)
    message = models.CharField(max_length=765, unique=True)

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.template_name

    def get_absolute_url(self):
        return reverse("messages:quick_message_templates_list")

    class Meta:
        ordering = ["-timestamp"]


class Settings(models.Model):

    mob_no = PhoneNumberField()
    password = models.CharField(max_length=120)
    message = models.CharField(max_length=765)

    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse("messages:quick_message_settings")

service_center/quick_messages/forms.py
from django import forms
from .models import Templates,Settings

class message_form(forms.Form):

    phone_numbers = forms.MultipleChoiceField()
    message = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

class TemplatesForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Templates

        fields = [
            "template_name",
            "message"
        ]


class SettingsForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Settings

        fields = [
            "mob_no",
            "password",
            "message"
        ]

service_center/cars/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist

from .models import Car

from django.contrib import messages

from .forms import CarForm

from django.core import serializers


@login_required()
def car_create(request):
    if not request.user.is_staff:
        raise Http404('User is not authorized by admin !!!')
    if not request.user.has_perm('cars.add_car'):
        raise Http404('User has no permission to do the following task !!!')
    form = CarForm(request.POST or None)
    print(form)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "successfully created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form": form,
        "title": "Create Vehicle"

    }
    return render(request, "car_form.html", context)


@login_required()
def car_detail(request, id=None):
    if not request.user.is_staff:
        raise Http404('User is not authorized by admin !!!')
    instance = get_object_or_404(Car, id=id)
    if request.is_ajax() and request.method == "GET" and request.GET['action'] == 'get_car_by_id':
        return HttpResponse(serializers.serialize('json', [instance]), content_type="application/json")
    context = {
        "car": instance,
        "title": "title list"
    }
    return render(request, "car_detail.html", context)


@login_required()
def car_list(request):
    if not request.user.is_staff:
        raise Http404('User is not authorized by admin !!!')

    queryset_list = Car.objects.all()

    if request.is_ajax() and request.method == "GET" and request.GET['action'] == 'get_car_for_customer':
        print("\n\n\n\n si hai")
        customer_id = request.GET['customer_id']
        try:
            queryset_list = Car.objects.filter(car_owner_id=customer_id)
            return HttpResponse(serializers.serialize('json', queryset_list), content_type="application/json")
        except ObjectDoesNotExist:
            print("Either the entry or blog doesn't exist.")

    if request.is_ajax() and request.method == "GET" and request.GET['action'] == 'get_cars':
        return HttpResponse(serializers.serialize('json', queryset_list), content_type="application/json")

    query = request.GET.get("query")
    if query:
        queryset_list = queryset_list.filter(
            Q(model_code__icontains=query) |
            Q(car_owner__full_name__contains=query) |
            Q(timestamp__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 10)  # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        query_set = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        query_set = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        query_set = paginator.page(paginator.num_pages)
    context = {
        "car_list": query_set,
        "title": "title list",
        "car_count": paginator.count
    }
    return render(request, "car_list.html", context)


@login_required()
def car_update(request, id=None):
    if not request.user.is_staff:
        raise Http404('User is not authorized by admin !!!')
    if not request.user.has_perm('cars.change_car'):
        raise Http404('User has no permission to do the following task !!!')
    instance = get_object_or_404(Car, id=id)
    form = CarForm(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "successfully updated")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "car": instance,
        "title": "Edit Vehicle",
        "form": form,
    }
    return render(request, "car_form.html", context)


@login_required()
def car_delete(request, id=None):
    if not request.user.is_staff:
        raise Http404('User is not authorized by admin !!!')
    if not request.user.has_perm('cars.delete_car'):
        raise Http404('User has no permission to do the following task !!!')
    if not request.user.is_staff and not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Car, id=id)
    instance.delete()
    messages.success(request, "successfully deleted")
    return redirect("car:list")

service_center/templates/employee_list.html
{% extends "base.html" %}

{% block content %}



<div class="row">

    <div class="col-sm-6 col-sm-offset-3">
        <form method="get" action="">
            <div class="input-group">
                <input type="text" name="query" placeholder="Search Employee" class="form-control" vaue="{{ request.GET.query }}"/>
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Go!</button>
      </span>
            </div>
        </form>
    </div>

</div>

<div class="container table-responsive">
    <h2>Employee List <span class="badge">{{ employee_list|length }}</span><a type="button" class="btn btn-primary btn-sm pull-right" href='{% url "employee:create" %}'>Create New One</a></h2>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th>Name</th>
            <th>Phone #</th>
            <th>Created @</th>
            <th>View</th>
             {% if perms.employee.change_employee %}
            <th>Edit</th>
            {% endif %}
            {% if perms.employee.delete_employee %}
            <th>Delete</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
       {% for employee in employee_list %}
        <tr>
            <td>{{ employee.full_name }}</td>
            <td>{{ employee.phone_number }} </td>
            <td>{{ employee.timestamp }}</td>
            <td><a type="button" class="btn btn-info btn-xs" href="{{employee.get_absolute_url}}">View</a></td>
            {% if perms.employee.change_employee %}
            <td><a type="button" class="btn btn-warning btn-xs" href='{% url "employee:update" id=employee.id %}'>Edit</a></td>
            {% endif %}
            {% if perms.employee.delete_employee %}
            <td><a type="button" class="btn btn-danger btn-xs" href='{% url "employee:delete" id=employee.id %}' data-confirm="true">Delete</a></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<center>

    {% if employee_list.has_other_pages %}
    <ul class="pagination">
        {% if employee_list.has_previous %}
        <li> <a href="?page={{ employee_list.previous_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in employee_list.paginator.page_range %}
        {% if employee_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if employee_list.has_next %}
        <li>
            <a href="?page={{ employee_list.next_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">&raquo;</a>
        </li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}

</center>

<script type="text/javascript">
    $('*[data-confirm="true"]').on('click', function() {
        return confirm("Are you sure?");
    });
</script>

{% endblock content %}

service_center/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href='{% url "order:create" %}'>Speedo Car Wash</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Home</a></li>-->
        {% if perms.customers.add_customer %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Customer <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href='{% url "customer:create" %}'>Create Customer</a></li>
            <li><a href='{% url "customer:list" %}'>Customer List</a></li>
          </ul>
        </li>
        {% endif %}
        {% if perms.cars.add_car %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Vehicle <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href='{% url "car:create" %}'>Create Vehicle</a></li>
            <li><a href='{% url "car:list" %}'>Vehicle List</a></li>
          </ul>
        </li>
        {% endif %}
        {% if perms.facilities.add_facilitie %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Facility <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href='{% url "facility:create" %}'>Create Facility</a></li>
            <li><a href='{% url "facility:list" %}'>Facility List</a></li>
          </ul>
        </li>
        {% endif %}
        {% if perms.discounts.add_discount %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Discount <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href='{% url "discounts:discounts_create" %}'>Create Discount</a></li>
            <li><a href='{% url "discounts:discounts_list" %}'>Discounts List</a></li>
          </ul>
        </li>
        {% endif %}
        {% if perms.expense.add_expensecategory %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Expense Category<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href='{% url "expense:create" %}'>Create Expense Category</a></li>
            <li><a href='{% url "expense:list" %}'>Expense Category List</a></li>
          </ul>
        </li>
        {% endif %}
        {% if perms.expense.add_expense %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Expenses<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href='{% url "expense:expense_create" %}'>Create Expense</a></li>
            <li><a href='{% url "expense:expense_list" %}'>Expenses List</a></li>
          </ul>
        </li>
        {% endif %}
        {% if perms.employee.add_employee %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Employee <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href='{% url "employee:create" %}'>Create Employee</a></li>
            <li><a href='{% url "employee:list" %}'>Employee List</a></li>
          </ul>
        </li>
        {% endif %}
        {% if perms.order.add_order %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Order <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href='{% url "order:create" %}'>Order Create</a></li>
            <li><a href='{% url "order:list" %}'>Order List</a></li>
          </ul>
        </li>
        {% endif %}
        {% if request.user.is_superuser or request.user.is_staff%}

            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reports <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  {% if request.user.is_staff and not request.user.is_superuser %}
                    <li><a href='{% url "reports:my_report" %}'>My Report</a></li>
                  {% elif request.user.is_superuser %}
                    <li><a href='{% url "reports:sales_breakdown" %}'>Sales Breakdown</a></li>
                    <li><a href='{% url "reports:car_count" %}'>Car Count</a></li>
                    <li><a href='{% url "reports:expense" %}'>Expenses</a></li>
                    <li><a href='{% url "reports:summary" %}'>Summary</a></li>
                    <li><a href='{% url "reports:my_report" %}'>My Report</a></li>
                  {% endif %}
              </ul>
            </li>

        {% endif %}

        {% if request.user.is_superuser %}

            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Quick Messages <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href='{% url "messages:quick_message" %}'>Quick Message</a></li>
                <li><a href='{% url "messages:quick_message_templates_create" %}'>Message Template Create</a></li>
                <li><a href='{% url "messages:quick_message_templates_list" %}'>Message Template List</a></li>
                <li><a href='{% url "messages:quick_message_settings" %}'>Default Message Settings</a></li>
              </ul>
            </li>

        {% endif %}
      </ul>
      {% endif %}

      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <!--**********************************************-->
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-user"></span> 
              {% if request.user.is_superuser %}
              <strong>Admin</strong>
              {% endif %}
              {% if request.user.is_staff and not request.user.is_superuser %}
              <strong>Manager</strong>
              {% endif %}
              <span class="glyphicon glyphicon-chevron-down"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <div class="navbar-login">
                  <div class="row">
                    <div class="col-lg-4">
                      <p class="text-center">
                        <span class="glyphicon glyphicon-user icon-size"></span>
                      </p>
                    </div>
                    <div class="col-lg-8">
                      <p class="text-left"><strong>{{request.user.first_name}} {{request.user.last_name}}</strong></p>
                      <p class="text-left small">{{request.user.email}}</p>
                      {% if request.user.is_superuser %}
                      <a type="button" href="{% url 'admin:index' %}" class="btn btn-primary btn-md">Admin Panel</a>
                      {% endif %}

                      <!--<p class="text-left">-->
                      <!--<a href="#" class="btn btn-primary btn-block btn-sm">Actualizar Datos</a>-->
                      <!--</p>-->
                    </div>
                  </div>
                </div>
              </li>
              <li class="divider"></li>
              <li>
                <div class="navbar-login navbar-login-session">
                  <div class="row">
                    <div class="col-lg-12">
                      <p>
                        <a href='{% url "auth_logout" %}' class="btn btn-danger btn-block"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
                      </p>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </li>
        </ul>

        <!--**************************************************-->

        <!--<li><a href='{% url "auth_logout" %}'><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>-->
        {% else %}
        <!--<li><a href='{% url "registration_register" %}'><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
        <li><a href='{% url "auth_login" %}'><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<style>
  .navbar-login
  {
    width: 305px;
    padding: 10px;
    padding-bottom: 0px;
  }

  .navbar-login-session
  {
    padding: 10px;
    padding-bottom: 0px;
    padding-top: 0px;
  }

  .icon-size
  {
    font-size: 87px;
  }
</style>